--------------------------------------------------------
-- Archivo creado  - viernes-setiembre-20-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOLETA
--------------------------------------------------------

  CREATE TABLE "BOLETA" 
   (	"BOLETA_ID" VARCHAR2(8 BYTE), 
	"FECHA" DATE, 
	"CLIENTE_ID" VARCHAR2(8 BYTE), 
	"MASCOTA_ID" VARCHAR2(8 BYTE), 
	"TRATAMIENTO_ID_PRINCIPAL" VARCHAR2(8 BYTE), 
	"TRATAMIENTO_ID_SECUNDARIO" VARCHAR2(8 BYTE), 
	"TOTAL_SIN_IGV" NUMBER(10,2), 
	"IGV" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ESTADO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CLIENTE" 
   (	"CLIENTE_ID" VARCHAR2(8 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MASCOTA
--------------------------------------------------------

  CREATE TABLE "MASCOTA" 
   (	"MASCOTA_ID" VARCHAR2(8 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ESPECIE" VARCHAR2(30 BYTE), 
	"EDAD" NUMBER(2,0), 
	"PESO" NUMBER(5,2), 
	"CLIENTE_ID" VARCHAR2(8 BYTE), 
	"VETERINARIO_ID" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRATAMIENTO
--------------------------------------------------------

  CREATE TABLE "TRATAMIENTO" 
   (	"TRATAMIENTO_ID" VARCHAR2(8 BYTE), 
	"NOMBRE_TRATAMIENTO" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VETERINARIO
--------------------------------------------------------

  CREATE TABLE "VETERINARIO" 
   (	"VETERINARIO_ID" VARCHAR2(8 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"ESPECIALIDAD" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"CONTRASEÑA" VARCHAR2(8 BYTE), 
	"DNI" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOLETA
SET DEFINE OFF;
REM INSERTING into CLIENTE
SET DEFINE OFF;
REM INSERTING into MASCOTA
SET DEFINE OFF;
REM INSERTING into TRATAMIENTO
SET DEFINE OFF;
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000000','Ninguno','0');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000001','Vacunación','45');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000002','Desparasitación','35');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000003','Esterilización','100');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000004','Urgencias','70');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000005','Cirugía','185');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000006','Cuidado Dental','25');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000007','Baño medicado','40');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000008','Corte de pelo','20');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000009','Corte de uñas','10');
Insert into TRATAMIENTO (TRATAMIENTO_ID,NOMBRE_TRATAMIENTO,PRECIO) values ('TR000010','Adiestramiento','70');
REM INSERTING into VETERINARIO
SET DEFINE OFF;
Insert into VETERINARIO (VETERINARIO_ID,NOMBRE,APELLIDOS,FECHA_NACIMIENTO,ESPECIALIDAD,TELEFONO,"CONTRASEÑA",DNI) values ('VT000001','ADMIN','ADMIN',to_date('30/03/99','DD/MM/RR'),'Jefe Veterinario','912345678','12345678','12345678');
--------------------------------------------------------
--  DDL for Index SYS_C008440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008440" ON "CLIENTE" ("CLIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008441
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008441" ON "VETERINARIO" ("VETERINARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008442
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008442" ON "MASCOTA" ("MASCOTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008445
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008445" ON "TRATAMIENTO" ("TRATAMIENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008446
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008446" ON "BOLETA" ("BOLETA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008446
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008446" ON "BOLETA" ("BOLETA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008440" ON "CLIENTE" ("CLIENTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008442
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008442" ON "MASCOTA" ("MASCOTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008445
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008445" ON "TRATAMIENTO" ("TRATAMIENTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008441
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008441" ON "VETERINARIO" ("VETERINARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOLETA
--------------------------------------------------------

  ALTER TABLE "BOLETA" ADD PRIMARY KEY ("BOLETA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLIENTE" ADD PRIMARY KEY ("CLIENTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MASCOTA
--------------------------------------------------------

  ALTER TABLE "MASCOTA" ADD PRIMARY KEY ("MASCOTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRATAMIENTO
--------------------------------------------------------

  ALTER TABLE "TRATAMIENTO" ADD PRIMARY KEY ("TRATAMIENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VETERINARIO
--------------------------------------------------------

  ALTER TABLE "VETERINARIO" ADD PRIMARY KEY ("VETERINARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
